# Generated by Django 5.0.6 on 2024-06-14 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('productname', models.CharField(max_length=100)),
                ('prize', models.IntegerField()),
                ('offer', models.CharField(max_length=50)),
                ('speed', models.CharField(max_length=50)),
                ('color', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=300)),
                ('category', models.CharField(max_length=50)),
                ('image', models.ImageField(upload_to='static/images/product/')),
            ],
        ),
    ]
